plugin:
  name: "HitChainAPI"
  version: "1.0.0"
  debug-mode: false
  language: "en"

features:
  enable-pvp: true
  enable-economy: true
  enable-quests: true

cooldowns:
  command-delay: 2 # in seconds
  ability-delay: 5

logging:
  level: INFO
  save-to-file: true
  log-file: logs/hitchain.log

performance:
  async-operations: true
  cache-size: 512

hooks:
  placeholderapi: true
  vault: true
  citizens: false

autoupdate:
  enabled: true
  check-interval: 3600 # in seconds
