name: HitChainAPI
main: com.hitchainapi.HitChainPlugin
version: 1.0.0
api-version: 1.13
description: The ultimate all-in-one Minecraft 1.8.9 API framework for PvP, economy, quests, and more.
author: CxmboFight
website: https://github.com/CxmboFight/HitChainAPI

commands:
  hitchain:
    description: Base command for HitChainAPI
    usage: /<command>
    permission: hitchain.command.use
    aliases: [hc, hca]

permissions:
  hitchain.*:
    description: Gives access to all HitChainAPI commands and features.
    default: op
    children:
      hitchain.command.use: true
      hitchain.admin: true
      hitchain.reload: true

  hitchain.command.use:
    description: Access to basic HitChainAPI commands
    default: true

  hitchain.admin:
    description: Access to administrative commands (debug, force actions)
    default: op

  hitchain.reload:
    description: Permission to reload plugin configurations
    default: op

softdepend:
  - PlaceholderAPI
  - Vault
  - Essentials
  - ProtocolLib
  - Citizens

load: POSTWORLD
loadbefore:
  - AnotherPluginThatUsesHitChain

libraries:
  - org.bstats:bstats-bukkit:3.0.0

